<?php

/*

 Copyright 2019 CNRS.

 This program is free software; you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation; either version 3 of the License,
 or (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>.

*/


namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogRepository extends EntityRepository
{
	public function selectAllExportCsv($date, $dateEnd) {
        $em = $this->getEntityManager();
        $date = new \DateTime($date);
        $dateEnd = new \Datetime($dateEnd);
        $dateEnd = $dateEnd->add(new \DateInterval('P1D'));
        $logs = $em->createQuery('SELECT u.name AS name, 
        			u.surname AS surname,
        			e.gepheId AS gepheId,
        			l.date AS datelog,
        			l.name AS logname,
        			l.description AS description,
        			u.username AS username
                    FROM AppBundle:Log l
                    INNER JOIN AppBundle:Entry e WITH l.entry = e.id 
                    INNER JOIN AppBundle:User u WITH l.user = u.id
                    WHERE l.date BETWEEN :date and :dateEnd
                    ORDER BY l.date DESC')->setParameters(array('date' => $date, 'dateEnd' => $dateEnd))->getResult();
        return $logs;

	}
}
